runtime: php #言語はphp
env: flex #GAEはstandardではなくflexible使うよ

runtime_config:
  document_root: public

skip_files: #ここに指定したものはGAEにアップロードされない
  - .env #セキュリティの観点から.envはあげない

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:CJkzptlHh+VUCHHc2fpMQbZ3FmReod535SFvBqZCb0U=
  STORAGE_DIR: /tmp